### ISSUE TITLE
<video> with <source> child

### ISSUE THREAD

**Issue by Nightbl927** [CatHood0/flutter_quill_delta_from_html#1]
Existing code accounts for the 'src' attribute in the `<video>` tag but not if the `<video>` tag has a child `<source>.` I have seen both versions of the `<video>` tag usage.

https://www.geeksforgeeks.org/html5-video/

I would submit a PR but I am not as familiar with using github in that manner yet.
```dart
  @override
  List<Operation> videoToOp(dom.Element element) {
    final String src = element.attributes['src'] ?? '';
    final String source_src = element.firstChild?.attributes['src'] ?? '';

    if (src.isNotEmpty) {
      return [
        Operation.insert('\n'),
        Operation.insert({'video': src})
      ];
    }
    else if(source_src.isNotEmpty) {
      return [
        Operation.insert('\n'),
        Operation.insert({'video': source_src})
      ];
    }

    return [];
  }
```
If you don't mind, I would like to contribute to your project as I am working on something that utlizes `HTML` to `Delta.`

**Comment by CatHood0** [comment]
Excellent, do the PR when you can and I'll be sure to test this functionality. While implementing `<video>` to `Operation`, I thought about this, however inadvertently it seems I didn't. 

Thanks in advance for the effort!

**Comment by CatHood0** [comment]
> final String source_src = element.firstChild?.attributes['src'] ?? '';

Even for this part, we could create a validation at the level of all the child nodes of `<video>` and check if the src of these is valid, and only take the first one which has a valid source (like a URL for example, in instead of something like this: `<source src="movies.mp4">` which is invalid, because `Delta` probably either from `QuillJs` or `flutter_quill` doesn't know where this file comes from)

**Comment by CatHood0** [comment]
At the current version (1.2.3) this is already implemented
