### ISSUE TITLE
Spaces outside the tag on both sides are lost

### ISSUE THREAD

**Issue by ddxl123** [CatHood0/flutter_quill_delta_from_html#10]
example:
```
I <strong>love</strong> programming.
```
lost:
```
Iloveprogramming.
```

example:
```
I <strong> love </strong> programming.
```
normal:
```
I love programming.
```

**Comment by CatHood0** [comment]
I'll check it as soon as i can. Thanks for reporting it.

**Comment by Uche01** [comment]
Yes @ddxl123 this is same issue I experienced. @CatHood0 kindly do. Very helpful package BTW

**Comment by CatHood0** [comment]
It's a bit more complicated to fix this, because we can't actually tell if the text we're correcting is inside an HTML element or not, which means that we can only enter a default behavior. You can see this [here](https://github.com/CatHood0/flutter_quill_delta_from_html/blob/75d669438597625d72d996cb2858b402d0b02a97/lib/parser/html_to_delta.dart#L47-L79) as well.

I'll try to fix it anyway, although it will take some time due to external factors.

**Comment by CatHood0** [comment]
@ddxl123 if the issue persists, report it.
