### ISSUE TITLE
DOM traversal

### ISSUE THREAD

**Issue by Nightbl927** [CatHood0/flutter_quill_delta_from_html#3]
should the processNode function in `html_utils` be similar to `resolveCurrentElement` in `html_to_operation` to allow for tags that are nested?

For example a `<video>` tag in a `<div>` will only display the link and not the video once converted to Delta.

**Comment by CatHood0** [comment]
The task of `processNode` is, as you say, to traverse nodes that are nested. Because, if we take for example: 

```html
<span><em>italic</em> with span</span>
```

Having more ethics within itself, we need a way to always go to the bottom to obtain any attribute or text and apply it with the corresponding format. The `processNode` method is only used to obtain the inline attributes and insert the corresponding `Operations` (this could be confusing, because it also searches within itself to see if the node is a `<br>` or a `<span>`, but this is only because inside a `<p>` a line break could perfectly fit a `<span>`)

Of course, do not confuse it with `resolveCurrentElement,` because this is only responsible for detecting what type of node it is (`<p>`, `<h1>`, `<img>`, etc.), and calling the corresponding functions. If you did a little digging, you will notice that it also verifies the attributes inline (something unusual because this part should only have one task: which is to call the functions according to the type of node), and this it does, because at least in `listToOp` in the default implementation, this method is used since a `<li>` can have all types of elements within itself (I do not rule out that the others do not).

**Comment by CatHood0** [comment]
It is not yet planned to create an implementation that adds the `<div>` to be part of the package since they could contain anything. If you have any suggestions or explanations as to why it would be beneficial to implement this in the package, you are more than welcome to say so.

If you need to detect a div, you could use `CustomHtmlParts`, which are used in a similar way to detect any `HTML` (if the validation matches) and convert it to an operation. Here is the example found in the README:

```dart
//Creating your own CustomHtmlPart (alternative to create CustomBlockEmbeds from custom html)

//First you need to define your own CustomHtmlPart

import 'package:flutter_quill_delta_from_html/flutter_quill_delta_from_html.dart';
import 'package:html/dom.dart' as dom;

/// Custom block handler for <div> elements.
class DivCustomBlock extends CustomHtmlPart {
  @override
  bool matches(dom.Element element) {
    return element.localName == 'div' && 
      element.nodes.where((node) => node is dom.Element && node.localName == 'video').firstOrNull != null;
  }

  @override
  List<Operation> convert(dom.Element element, {Map<String, dynamic>? currentAttributes}) {
    final Delta delta = Delta();
  
    //here you can set your customl logic search the video node into the `<div>` and create a Operation
    return delta.toList();
  }
}

//After, put your DivCustomBlock to HtmlToDelta using the param customBlocks

void main() {
  // Example HTML snippet
  final htmlText = '''
    <html>
      <body>
        <div><video src="url_to_video"></video></div>
      </body>
    </html>
  ''';

  // Registering the custom block
  final customBlocks = [DivCustomBlock()];

  // Initialize HtmlToDelta with the HTML text and custom blocks
  final converter = HtmlToDelta(customBlocks: customBlocks);

  // Convert HTML to Delta operations
  final delta = converter.convert(htmlText);
}
```

**Comment by Nightbl927** [comment]
Thanks, CatHood. I think my usecase is a bit different. What I want to do is parse through a website and convert it to Delta. Understandably, there will be no way to convert every situation.

In this process, I will come across elements that will be wrapped in a `<div>`. It will also be very possible to have a `<video>` tag wrapped in a `<span>, <div> or <p>` also. This is the reason for wanting both a way to parse through `<div>` and also traverse it like the original `resolveCurrentElement`. With the current use of `processNode` a `<video>` wrapped in any other element will just result in a link due to the `videoToTop` not triggering.

I hope this helps with why I wanted to see if these features could be implemented. If this isn't the use case you were envisioning, don't worry about it! I don't want to add extraneous functionality that only I use. Amazing job you have done with this!

**Comment by CatHood0** [comment]
You have a point. I'll take about it at the next update

**Comment by CatHood0** [comment]
> I will come across elements that will be wrapped in a `<div>`- It will also be very possible to have a `<video>` tag wrapped in a `<span>`, `<div>` or `<p>`

Iis good to know that this type of situation exists, I will take it into account for future references.

> It will also be very possible to have a `<video>` tag wrapped in a `<span>`, `<div>` or `<p>` also

You can make a PR for this part, as I can implement the use of `<div>` and make it parsable like the current `HTML` elements. However, it is difficult for me to know how I could allow more complexity, because we can have, for example, `HTML` like this:

```html
<p style="font-size: 12px;font-family: Times new roman"> text <video src="url"></video> more text</p>
```

The part of detecting these elements is simple, however, when it comes time to create `Operations`, this is where everything gets complicated, because you have to take into account any attribute that the `<p>` tag has and you also have to separate correctly the video from the rest of the text (in addition to only applying attributes that correspond to the attribute type). It gets a little cumbersome at that point.

If you have any ideas on how you want to implement this, you are more than welcome to make a PR.

**Comment by Nightbl927** [comment]
I am thinking that processNode will need to be updated to identify all of the elements that are found in resolveCurrentElement. Or ideally make resolveCurrentElement recursive (I believe the processElement is the recursive section that iterates through the DOM but it does not account for making the video).

I can try to see if I can play around with the code and submit a PR but I am more of the hacking away at code type rather than making something that makes sense for others and "good" code.

**Comment by CatHood0** [comment]
> I am thinking that processNode will need to be updated to identify all of the elements that are found in resolveCurrentElement. Or ideally make resolveCurrentElement recursive (I believe the processElement is the recursive section that iterates through the DOM but it does not account for making the video).

I'll add partial support for this tag

**Comment by CatHood0** [comment]
At the current version (1.2.5) was added `<div>` support.

**Comment by Nightbl927** [comment]
Thank you, @CatHood0! The functionality you added to allow for child video and image tags works great!
