### ISSUE TITLE
Multiple paragraphs tags

### ISSUE THREAD

**Issue by john-fly** [CatHood0/flutter_quill_delta_from_html#6]
The multiple paragraphs seem to be merged into one paragraph.

```
<p><strong>sdf</strong></p>
<p><em>ttw</em></p>
<p><u>sdf</u></p>
```

become:

![image](https://github.com/user-attachments/assets/e70ed572-1b3d-4b11-93bf-6eb7ce10670b)

**Comment by raimkulovr** [comment]
I believe the problem is here:
[https://github.com/CatHood0/flutter_quill_delta_from_html/blob/44f7d90a4c0395f9e326f74191b87c22bf55fb96/lib/parser/html_to_delta.dart#L173](https://github.com/CatHood0/flutter_quill_delta_from_html/blob/44f7d90a4c0395f9e326f74191b87c22bf55fb96/lib/parser/html_to_delta.dart#L173)
``` dart 
List<Operation> nodeToOperation(dom.Node node, HtmlOperations htmlToOp) {
    List<Operation> operations = [];
    if (node is dom.Text) {
      operations.add(Operation.insert(node.text.trim()));
    }
    if (node is dom.Element) {
      List<Operation> ops = htmlToOp.resolveCurrentElement(node);
      operations.addAll(ops);
    }

    return operations;
  }
```

When I removed `.trim()` in the local copy of this package, it seemed to solve both some of my problems and the issue addressed here.
![image](https://github.com/user-attachments/assets/5e573eaf-e51f-45b8-8313-cc3438978198)
